MODE: dev
PROJECT_NAME: MyProject
SERVER_NAME: MyServer

#PROTOCOL: https
BACKEND_HOST: localhost
BACKEND_PORT: 8080
API_V1_STR: "/api/v1"

WORKERS: 8

FIRST_SUPERUSER: "ashwin.rachha@gmail.com"
FIRST_SUPERUSER_PASSWORD: "123456"

SECRET_KEY: 28472B4B6250655368566D5971337436763979244226452948404D635166546A

SESSION_EXPIRE_TIME: 3600
SESSION_EXPIRE_TIME_EXTENDED: 2592000
TWO_FA_TIMEOUT: 12000
PASSWORD_LESS_CREATE_TIMEOUT: 360

FRONTEND_HOST: localhost
FRONTEND_PORT: 3001

STATIC_HOST: localhost
STATIC_PORT: 8081

UPLOAD_DIR_ROOT: "../file_server"

BACKEND_CORS_ORIGINS:
  - http://localhost:3001
  - http://localhost

ALLOWED_EMAIL_HOST:
  - gmail.com

POSTGRES_SERVER: ""
POSTGRES_USER: ""
POSTGRES_PASSWORD: ""
POSTGRES_DB: ""

REDIS_HOST: ""
REDIS_PORT: ""
REDIS_PASSWORD: ""

SMTP_TLS: False
SMTP_PORT: 1025
SMTP_HOST: localhost
SMTP_USER: smptuser
SMTP_PASSWORD: smtppass

EMAILS_FROM_EMAIL: "ashwin.rachha@gmail.com"
EMAIL_RESET_TOKEN_EXPIRE_HOURS: 48
EMAIL_VERIFY_EXPIRE_HOURS: 48
EMAIL_TEMPLATES_DIR: templates/email-templates/

USERS_OPEN_REGISTRATION: True
